green_jacket/green_jacket/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path(
        'green_jacket/',
        include(
            ('green_jacket_app.urls', "green_jacket_app"),
            namespace="green_jacket_app"
        )
    ),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path(r'^__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

green_jacket/green_jacket_app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('home/', views.home, name="home"),
    path('login/', views.login_view, name="login_view"),
    path('logout/', views.logout_view, name="logout_view"),
    path('toogle_dark_mode/', views.toogle_dark_mode, name="toogle_dark_mode"),
    path('brand_models/', views.brand_models, name="brand_models"),
    path('brands/', views.brands, name="brands"),
    path('green_score/', views.green_score, name="green_score"),
    path('toogle_favorite/', views.toogle_favorite, name="toogle_favorite"),
]

green_jacket/green_jacket_app/models.py
from django.db.models import F, Sum, Case, When

from django.db import models

class UserCustom(models.Model):
    name = models.CharField(max_length=50)
    dark_mode = models.BooleanField(default=False)

class BuildProcess(models.Model):
    name = models.CharField(max_length=50)
    image_url = models.CharField(max_length=5000)
    score = models.IntegerField()

class Material(models.Model):
    name = models.CharField(max_length=50)
    image_url = models.CharField(max_length=5000)
    score = models.IntegerField()

class Country(models.Model):
    name = models.CharField(max_length=50)
    image_url = models.CharField(max_length=5000)
    score = models.IntegerField()

class Brand(models.Model):
    name    = models.CharField(max_length=50)
    image_url = models.CharField(max_length=5000)

    def get_score(self):
        score = 0
        score_count = 0
        for brand_model in self.brand_models.all():
            score += brand_model.get_score()
            score_count += 1
        return int(score / score_count)

class BrandModel(models.Model):
    date    = models.DateField()
    name    = models.CharField(max_length=50)
    type    = models.CharField(max_length=50)
    link    = models.CharField(max_length=500)
    material= models.ForeignKey(Material, related_name="brand_models", on_delete=models.CASCADE)
    country = models.ForeignKey(Country, related_name="brand_models", on_delete=models.CASCADE)
    build_process = models.ForeignKey(BuildProcess, related_name="brand_models", on_delete=models.CASCADE)
    brand   = models.ForeignKey(Brand, related_name="brand_models", on_delete=models.CASCADE)
    image_url = models.CharField(max_length=5000)
    tarif = models.FloatField()
    favorite = models.BooleanField(default=False)

    def get_score(self):

        return self.material.score + self.country.score + self.build_process.score

class Favorite(models.Model):
    user = models.ForeignKey(UserCustom, related_name="favorites", on_delete=models.CASCADE)
    brand_model = models.ForeignKey(BrandModel, related_name="favorites", on_delete=models.CASCADE)

green_jacket/green_jacket_app/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse

from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy


from green_jacket_app.models import Brand, UserCustom, BrandModel, Favorite

def get_colors(is_dark_mode):

    colors = [
        [
            {"1": "#001011", "2":"#042629"},
            {"1": "#FFFFFF", "2":"#FFFFFF"}
        ],
        [
            {"1": "#0F4637", "2":"#266856"},
            {"1": "#A2E1C4", "2":"#93d5b7"}
        ],
        [
            {"1": "#EBD82D", "2":"#f8e74f"},
            {"1": "#001011", "2":"#042629"}
        ]
    ]
    text = ["#FFFFFF", "#001011"]

    index = 0 if is_dark_mode else 1

    return {
        "color1" : colors[0][index],
        "color2" : colors[1][index],
        "color3" : colors[2][index],
        "text": text[index]
    }

def get_context(request):
    context = {}
    try:
        user_name = request.user
        user_custom = UserCustom.objects.get(name=user_name)
        context["dark_mode"] = user_custom.dark_mode
        context["user"] = user_name
        context["connected"] = True
    except:
        context["dark_mode"] = False
        context["connected"] = False

    context["current_path"] = request.path
    context["colors"] = get_colors(context["dark_mode"])
    return context

def signup(request):
    context = get_context(request)
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            user_name = user.username
            user_custom = UserCustom(name=user_name)
            user_custom.save()
            login(request, user)
            return redirect('/green_jacket/home')  # Rediriger vers la page d'accueil ou une autre page
    else:
        form = UserCreationForm()
    context['form'] = form
    return render(request, 'registration/signup.html', context)

@login_required
def home(request):
    # La vue pour la page d'accueil, vous pouvez personnaliser cela

    context = get_context(request)
    return render(request, 'green_jacket/home.html', context)

@login_required
def green_score(request):

    context = get_context(request)
    return render(request, 'green_jacket/green_score.html', context)

def login_view(request):
    context = get_context(request)
    next_params = get_params(request, "next")
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if next_params not in ["None", None, ""]:
                return redirect(next_params)
            else:
                return redirect('/green_jacket/home')
    else:
        form = AuthenticationForm()
    context['form'] = form
    return render(request, 'registration/login.html', context)

def logout_view(request):
    logout(request)
    return redirect('/green_jacket/login')

@login_required
def toogle_dark_mode(request):

    context = get_context(request)
    get_params = request.GET
    next_params = get_params.get("next")

    user_custom = UserCustom.objects.get(name=context["user"])
    user_custom.dark_mode = not user_custom.dark_mode
    user_custom.save()

    return redirect(next_params)

@login_required
def toogle_favorite(request):

    context = get_context(request)
    brand_model_id = get_params(request, "brand_model_id")
    type_selected = get_params(request, "type")
    brand_selected = get_params(request, "brand")
    favorite_selected = get_params(request, "favorite")

    user_custom = UserCustom.objects.get(name=context["user"])
    brand_model = BrandModel.objects.get(id=brand_model_id)

    favorite = Favorite.objects.filter(user=user_custom).filter(brand_model=brand_model)
    if len(favorite) == 0:
        favorite = Favorite(
            user=user_custom,
            brand_model=brand_model
        )
        favorite.save()
    else:
        favorite.delete()

    return redirect(f"/green_jacket/brand_models?brand={brand_selected}&type={type_selected}&favorite={favorite_selected}")

def get_params(request, param):
    get_params = request.GET
    return get_params[param] if param in get_params else None

@login_required
def brands(request):

    context = get_context(request)

    brands = Brand.objects.all()

    brands = [brand for brand in brands]
    brands.sort(key=lambda brand:-brand.get_score())

    context["brands"] = brands

    return HttpResponse(render(request, "green_jacket/brands.html", context))

@login_required
def brand_models(request):

    context = get_context(request)

    user_custom = UserCustom.objects.get(name=context["user"])

    brand_selected = get_params(request, "brand")
    favorite_selected = get_params(request, "favorite")
    brand_model_type_selected = get_params(request, "brand_model_type")
    context["brand_selected"] = brand_selected
    context["brand_model_type_selected"] = brand_model_type_selected

    brands_to_filter = Brand.objects.all()
    brands_to_filter = [brand for brand in brands_to_filter]

    brand_model_types_to_filter = [brand_model["type"] for brand_model in BrandModel.objects.all().values("type").distinct()]

    brand_models = BrandModel.objects.all()
    if brand_selected not in ("", None, "None"):
        brand_models = brand_models.filter(brand__name=brand_selected)
    if brand_model_type_selected not in ("", None, "None"):
        brand_models = brand_models.filter(type=brand_model_type_selected)

    brand_models = [model for model in brand_models]

    if favorite_selected == 'on':
        new_brand_models=[]
        for brand_model in brand_models:
            favorite = Favorite.objects.filter(user=user_custom).filter(brand_model=brand_model)
            if len(favorite) == 0:
                pass
            else:
                new_brand_models.append(brand_model)
        brand_models = new_brand_models

    brand_models.sort(key=lambda model:-model.get_score())

    for brand_model in brand_models:
        favorite = Favorite.objects.filter(user=user_custom).filter(brand_model=brand_model)
        if len(favorite) == 0:
            brand_model.favorite = False
        else:
            brand_model.favorite = True

    context["brand_models"] = brand_models
    context["brands_to_filter"] = brands_to_filter
    context["brand_model_types_to_filter"] = brand_model_types_to_filter
    context["favorite_selected"] = favorite_selected

    return HttpResponse(render(request, "green_jacket/brand_models.html", context))

green_jacket/green_jacket_app/templates/green_jacket/base.html
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        {% load static %}

        <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">

        <link href="https://www.dafontfree.net/embed/bHV0aGllci1yZWctcmVndWxhciZkYXRhLzE2Mi9sLzE5MzQ4MS9MdXRoaWVyLVJlZ3VsYXIudHRm" rel="stylesheet" type="text/css"/>
        <!-- others css -->
        <!-- <link rel="stylesheet" href="{% static 'css/typography.css' %}"> -->
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        <link rel="stylesheet" href="{% static 'css/responsive.css' %}">

        <div style="padding: 25px; background:linear-gradient(to right, {{colors.color1.1}}, {{colors.color1.2}})">


            <div class="row main-police" style="text-align:center; font-size:50px">
                <div class="col">
                    <a style="color:{{colors.color3.1}}; text-decoration:none" href="{% url 'green_jacket_app:home' %}"><strong>GREEN</strong> SCORE</a>
                </div>
                <div class="col">
                    <a style="color:{{colors.color3.1}}; text-decoration:none" href="{% url 'green_jacket_app:brands' %}">Marques</a>
                </div>
                <div class="col">
                    <a style="color:{{colors.color3.1}}; text-decoration:none" href="{% url 'green_jacket_app:brand_models' %}">Modèles</a>
                </div>
                <div class="col">
                    <a style="color:{{colors.color3.1}}; text-decoration:none" href="{% url 'green_jacket_app:green_score' %}">Green Score</a>
                </div>
                <div class="col" style="font-size:20px">
                    <a style="color:{{colors.text}}; text-decoration:none" href="{% url 'green_jacket_app:signup' %}">Sign Up</a>
                    <a style="color:{{colors.text}}; text-decoration:none" href="{% url 'green_jacket_app:login_view' %}">login</a>
                    <a style="color:{{colors.text}}; text-decoration:none" href="{% url 'green_jacket_app:logout_view' %}">logout</a>
                    {% if connected %}
                        <a style="color:{{colors.text}}; text-decoration:none" href="{% url 'green_jacket_app:toogle_dark_mode' %}?next={{current_path}}">{% if dark_mode %}Light{% else %}Dark{% endif %} Mode</a>
                    {% endif %}
                </div>

            </div>
        </div>
    </head>

    <body class="row main-police" style="background:linear-gradient(to right, {{colors.color2.1}}, {{colors.color2.2}}); color:{{colors.text}}"">
        <div style="margin:10px">
            {% block content %}{% endblock %}
        </div>
    </body>

</html>

green_jacket/green_jacket_app/templates/green_jacket/brand_models.html
{% extends 'green_jacket/base.html' %}

{% block content %}


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- Title -->
    <h1 style="text-align:center; font-size:70px; color:{{colors.color3.1}}">Les Modèles</h1>

    <div style="text-align: center;">
    <form method="GET" id="brandFormFilter" class="filter" action="{% url request.resolver_match.view_name %}">

        <label for="brand-select"><h2>Marque:</h2></label>
        <select name="brand" onchange="if (this.form.className == 'filter') this.form.submit()">
            <option value="">Tout</option>
            {% for brand in brands_to_filter %}
                {% if brand.name == brand_selected %}
                    <option value={{brand.name}} selected>{{brand.name}}</option>
                {% else %}
                    <option value={{brand.name}}>{{brand.name}}</option>
                {% endif %}
            {% endfor %}
        </select>

   
        <label for="type-select"><h2>Type:</h2></label>
        <select name="brand_model_type" onchange="if (this.form.className == 'filter') this.form.submit()">
            <option value="">Tout</option>
            {% for brand_model_type in brand_model_types_to_filter %}
                {% if brand_model_type == brand_model_type_selected %}
                    <option value={{brand_model_type}} selected class="title" >{{brand_model_type}}</option>
                {% else %}
                    <option value={{brand_model_type}}>{{brand_model_type}}</option>
                {% endif %}
            {% endfor %}
        </select>
  
        <label for="favorite-checkbox"><h2>Mes Favoris:</h2></label>
        {% if favorite_selected == 'on' %}
            <input
                type="checkbox"
                id="favorite"
                name="favorite"
                onchange="if (this.form.className == 'filter') this.form.submit()"
                checked
            ></input>
        {% else %}
            <input
                type="checkbox"
                id="favorite"
                name="favorite"
                onchange="if (this.form.className == 'filter') this.form.submit()"
            ></input>
        {% endif %}

    </form>
</div>
    
    <div class="row">

        <div class="col-10">
            <div class="row">
                <table>
                    {% for brand_model in brand_models %}
                        <tr>
                            <td valign="top" style="text-align:right">
                                <a href="{{ brand_model.link }}">
                                    <img style="height: 700px" src="{{ brand_model.image_url }}"/>
                                </a>
                                </br>
                                <h3>
                                    <a style="color:{{colors.text}}; text-decoration:none" href="{% url 'green_jacket_app:toogle_favorite' %}?brand_model_id={{ brand_model.id }}&type={{brand_model_type_selected}}&brand={{brand_selected}}&favorite={{favorite_selected}}">
                                        {% if brand_model.favorite %}
                                            <span class="glyphicon glyphicon-heart"></span> 
                                        {% else %}
                                            <span class="glyphicon glyphicon-heart-empty"></span>
                                        {% endif %}
                                    </a>
                                    {{ brand_model.name }}
                                </h3>
                            </td>
                            <td valign="top" style="text-align:left">
                                <a href="{% url 'green_jacket_app:brand_models' %}?brand={{ brand_model.brand.name }}">
                                    <img style="height: 350px" src="{{ brand_model.brand.image_url }}"/>
                                </a>
                                </br>
                                <h4> Marque {{ brand_model.brand.name }}</h4>
                                <h5> (Green Score Moyen : <strong>{{brand_model.brand.get_score}}</strong>)</h5>
                                <table>
                                    <tr>
                                        <td>
                                            <br/>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <h2>Green Score :</h2>
                                        </td>
                                        <td>
                                            <h2><strong>{{ brand_model.get_score }}</strong></h2>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <h4>Provenance :</h4>
                                        </td>
                                        <td>
                                            <img style="height: 25px" src="{{ brand_model.country.image_url }}"/>
                                        </td>
                                    </tr>
                                    <tr>
                                    <td>
                                        <h4>Matériel :</h4>
                                    </td>
                                    <td>
                                        <h4><strong>{{ brand_model.material.name }}</strong></h4>
                                    </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <h4>Fabrication :</h4>
                                        </td>
                                        <td>
                                            <h4><strong>{{ brand_model.build_process.name }}</strong></h4>
                                        </td>

                                    </tr>
                                    <tr>
                                        <td>
                                            <br/>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <br/>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <h3>Prix :</h3>
                                        </td>
                                        <td>
                                            <h3><strong>€ {{ brand_model.tarif }}</strong></h3>
                                        </td>

                                    </tr>
                                </table>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <br/>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>

    

{% endblock %}

green_jacket/green_jacket_app/templates/green_jacket/green_score.html
{% extends 'green_jacket/base.html' %}

{% block content %}

<style>
  .container {
            max-width: 800px;
            margin: 0 auto;
        }
        .article {
            text-align: left;
            margin: 20px 0;
            position: relative;
        }
        .article img {
            max-width: 200px;
            position: absolute;
            top: 0;
            left: -50px; /* Ajustez cette valeur pour déplacer l'image vers la gauche */
        }
        .article .content {
            margin-left: 170px; /* Ajustez cette marge pour aligner le texte à droite de l'image */
        }
</style>

<!-- Title -->
<h1 style="text-align:center; font-size:70px; color:{{colors.color3.1}}">Les Conseils Green</h1>

  <div class="container">


  <div class="article">
      <img src="https://www.craftine.com/media/catalog/product/cache/b7fd566cb3fd8bb5e0e17db7c1de0fcf/t/n/tn_03987_002.jpg" alt="Image 2">
      <div class="content">
          <h2>Jean</h2>
          <p>Les jeans, bien qu'indémodables, ont un impact environnemental considérable. Leur production nécessite d'importantes quantités d'eau et de ressources, contribuant à la pénurie d'eau et à la dégradation de l'environnement. De plus, les processus de teinture et de finition des jeans peuvent être polluants. Choisir des alternatives plus durables dans notre garde-robe peut aider à réduire notre empreinte écologique.</p>
      </div>
  </div>

  <div class="article">
    <img src="https://www.cousette.com/4755/tissu-lin-lave-naturel.jpg" alt="Image 3">
    <div class="content">
        <h2>Lin</h2>
        <p>Le lin est un choix écologique pour la mode. Il pousse naturellement avec peu d'irrigation et de pesticides, préservant ainsi les ressources en eau et la biodiversité. Sa production génère moins d'émissions de carbone que d'autres fibres, contribuant à la lutte contre le changement climatique. De plus, le lin est biodégradable, ce qui en fait une option respectueuse de l'environnement pour notre garde-robe.</p>
    </div>
</div>

  <div class="article">
      <img src="https://www.lamerceriedescreateurs.fr/7397-large_default/tissu-coton-bleu-roi-evira.jpg" alt="Image 3">
      <div class="content">
          <h2>Coton</h2>
          <p>Le tissu en coton est un allié précieux pour l'environnement. Cultivé de manière durable, il nécessite moins d'eau que d'autres fibres, favorise la biodiversité et réduit les émissions de carbone. En fin de vie, il est biodégradable, contribuant ainsi à la réduction des déchets textiles. Opter pour le coton, c'est choisir une option éco-responsable pour notre planète.</p>
      </div>
  </div>

  <div class="article">
    <img src="https://www.naturellementchanvre.com/9546-thickbox_default/nemo-toile-d-embourrure-chanvre.jpg" alt="Image 3">
    <div class="content">
        <h2>Chanvre</h2>
        <p>Le chanvre est un champion de la durabilité. Il pousse rapidement, nécessite peu d'eau et aucun pesticide, préservant ainsi les ressources naturelles et la biodiversité. Sa culture contribue à améliorer la qualité du sol et à réduire les émissions de carbone. Les textiles en chanvre sont non seulement écologiques, mais aussi durables, faisant de cette fibre un choix responsable pour la mode.</p>
    </div>
</div>

<div class="article">
  <img src="https://www.batiproduits.com/img/isolant-en-textile-recycle-en-vrac-pour-combles-perdus-isonat-cotonwool-002555873-product_maxi.jpg" alt="Image 3">
  <div class="content">
      <h2>Fibre Recyclée</h2>
      <p>Les tissus en fibres recyclées sont des héros de la durabilité. Ils réduisent la demande de nouvelles matières premières, minimisent les déchets textiles et limitent la pollution associée à la production de nouveaux textiles. En choisissant des textiles recyclés, nous contribuons à la préservation des ressources, à la réduction des émissions de carbone et à la promotion de l'économie circulaire, favorisant ainsi un avenir plus vert pour la mode.</p>
  </div>
</div>

</div>

<div>
    <br/>
</div>
<div>
  <br/>
</div>
<div>
  <br/>
</div>
<div>
  <br/>
</div>

<div style="text-align: center;">
<iframe width="800" height="500" src="https://www.youtube.com/embed/bVVKW6kleGM?si=pACgD1Jtuqwm4tW4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
</div>
{% endblock %}

green_jacket/green_jacket_app/templates/green_jacket/home.html
{% extends 'green_jacket/base.html' %}

{% block content %}
<div class="login-container" style="text-align: center;">
  <h2>Bonjour {{user}}.</h2>
  <h2>Bienvenue sur <span style="color:{{colors.color3.1}}">Green Score</span></h2>
</div>
{% endblock %}